#sensor unification for differ platform
obj-$(CONFIG_HUAWEI_SENSORS_INPUT_INFO)	+= sensor_info.o
obj-y   += arch_type/
obj-y	+= gyroscope/
obj-y	+= light/
obj-y	+= accelerometer/
obj-y	+= compass/
#obj-$(TOUCHSCREEN_RMI4_SYNAPTICS_GENERIC) += synaptics_generic.o	
obj-y   += touchscreen/
obj-$(CONFIG_HUAWEI_TOUCH_INPUT_INFO)+= touch_info.o
