# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_FEATURE_IRDA_SC16IS750)  += nxp_sc16is750.o
obj-$(CONFIG_HUAWEI_FEATURE_IRDA_GPIO_SIMULATION)  += irda_gpio_simulation.o