/* This file is auto-generated by tool, please don't manully modify it.*/

#include <hsad/config_boardids.h>

#include "hw_U9508_configs.c"
#include "hw_U9510D_configs.c"
#include "hw_U9510E_configs.c"
#include "hw_vdcs_k3oem_configs.c"
#include "hw_U9510_configs.c"
#include "hw_vacs_k3oem_configs.c"
#include "hw_CS_U9510_configs.c"
#include "hw_CS_U9510_VC_configs.c"
#include "hw_apu1ve_k3oem_configs.c"
#include "hw_vccs_k3oem_configs.c"
extern struct board_id_general_struct config_power_U9508;
extern struct board_id_general_struct config_power_U9510D;
extern struct board_id_general_struct config_power_U9510E;
extern struct board_id_general_struct config_power_vdcs_k3oem;
extern struct board_id_general_struct config_power_U9510;
extern struct board_id_general_struct config_power_vacs_k3oem;
extern struct board_id_general_struct config_power_CS_U9510;
extern struct board_id_general_struct config_power_CS_U9510_VC;
extern struct board_id_general_struct config_power_apu1ve_k3oem;
extern struct board_id_general_struct config_power_vccs_k3oem;

/*gpio perl producted data*/
#ifdef CONFIG_HUAWEI_GPIO_UNITE
extern struct board_id_general_struct config_gpio_U9508;
extern struct board_id_general_struct config_pm_gpio_U9508;
extern struct board_id_general_struct config_gpio_U9510D;
extern struct board_id_general_struct config_pm_gpio_U9510D;
extern struct board_id_general_struct config_gpio_U9510E;
extern struct board_id_general_struct config_pm_gpio_U9510E;
extern struct board_id_general_struct config_gpio_vdcs_k3oem;
extern struct board_id_general_struct config_pm_gpio_vdcs_k3oem;
extern struct board_id_general_struct config_gpio_U9510;
extern struct board_id_general_struct config_pm_gpio_U9510;
extern struct board_id_general_struct config_gpio_vacs_k3oem;
extern struct board_id_general_struct config_pm_gpio_vacs_k3oem;
extern struct board_id_general_struct config_gpio_CS_U9510;
extern struct board_id_general_struct config_pm_gpio_CS_U9510;
extern struct board_id_general_struct config_gpio_CS_U9510_VC;
extern struct board_id_general_struct config_pm_gpio_CS_U9510_VC;
extern struct board_id_general_struct config_gpio_apu1ve_k3oem;
extern struct board_id_general_struct config_pm_gpio_apu1ve_k3oem;
extern struct board_id_general_struct config_gpio_vccs_k3oem;
extern struct board_id_general_struct config_pm_gpio_vccs_k3oem;
#endif

/*total table*/
struct board_id_general_struct  *hw_ver_total_configs[] =
{
#ifdef CONFIG_HUAWEI_GPIO_UNITE
    &config_gpio_U9508, //gpio
    &config_gpio_U9510D, //gpio
    &config_gpio_U9510E, //gpio
    &config_gpio_vdcs_k3oem, //gpio
    &config_gpio_U9510, //gpio
    &config_gpio_vacs_k3oem, //gpio
    &config_gpio_CS_U9510, //gpio
    &config_gpio_CS_U9510_VC, //gpio
    &config_gpio_apu1ve_k3oem, //gpio
    &config_gpio_vccs_k3oem, //gpio
#endif
#ifdef CONFIG_HUAWEI_GPIO_UNITE
    &config_pm_gpio_U9508, //pm gpio
    &config_pm_gpio_U9510D, //pm gpio
    &config_pm_gpio_U9510E, //pm gpio
    &config_pm_gpio_vdcs_k3oem, //pm gpio
    &config_pm_gpio_U9510, //pm gpio
    &config_pm_gpio_vacs_k3oem, //pm gpio
    &config_pm_gpio_CS_U9510, //pm gpio
    &config_pm_gpio_CS_U9510_VC, //pm gpio
    &config_pm_gpio_apu1ve_k3oem, //pm gpio
    &config_pm_gpio_vccs_k3oem, //pm gpio
#endif
    &config_common_U9508, //common xml
    &config_common_U9510D, //common xml
    &config_common_U9510E, //common xml
    &config_common_vdcs_k3oem, //common xml
    &config_common_U9510, //common xml
    &config_common_vacs_k3oem, //common xml
    &config_common_CS_U9510, //common xml
    &config_common_CS_U9510_VC, //common xml
    &config_common_apu1ve_k3oem, //common xml
    &config_common_vccs_k3oem, //common xml
};
