/* This file is auto-generated by tool, DO NOT modify it manully. */

#ifndef CONFIG_BOARDIDS_H
#define CONFIG_BOARDIDS_H

#define BOARD_ID_U9508   71
#define BOARD_ID_U9510D   118
#define BOARD_ID_U9510E   102
#define BOARD_ID_VDCS_K3OEM   17
#define BOARD_ID_U9510   119
#define BOARD_ID_VACS_K3OEM   1
#define BOARD_ID_CS_U9510   103
#define BOARD_ID_CS_U9510_VC   87
#define BOARD_ID_APU1VE_K3OEM   18
#define BOARD_ID_VCCS_K3OEM   16

#endif
