#
# EternityProject drivers and routines for nVidia Tegra
#
# Copyright (C) 2012-2013 EternityProject Development
# Angelo G. Del Regno <kholk11@gmail.com>
# Joel Low <joel@joelsplace.sg>
#
# This software is GPL.

subdir-ccflags-y := -Wno-error

obj-$(CONFIG_EPRJ_CPUMANAGER)		+= eprj_t3_cpumanager.o
obj-$(CONFIG_EPRJ_CPUMANAGER)		+= eprj_scheduling.o
obj-$(CONFIG_EPRJ_SYSFS_TOOLS)		+= eprj_sysfs_tools.o
obj-$(CONFIG_ETERNITYPROJECT_LIVECOLOR) += eprj_livecolor.o
obj-$(CONFIG_EPRJ_FAN_MANAGEMENT)	+= eprj_tegra_fan.o
