/*************************************************************
 *CAUTION : This file is Auto Generated by gen_io_cfg.pl based on *.xls
 *so,don't modify this file manually!
 *************************************************************/
#ifndef __E_IOMUX_PHONE_CS_H__
#define __E_IOMUX_PHONE_CS_H__
#include "iomux.h"
#include "k3v2_iomux_pins.h"
#include <hsad/config_interface.h>

extern struct iomux_ops iomux_block_ops;
#define IOMUX_BLOCK(_iomux_block, _block_name, _block_func, _pins)	\
struct iomux_block _iomux_block = {\
	.block_name  = _block_name,\
	.block_func   =  _block_func,\
.pins = _pins,\
.ops = &iomux_block_ops,\
.init = 0,\
};


/******************pins ****************/

struct  iomux_pin *i2c0_u9510_cs_pins[] = {
&gpio_084_cs, &gpio_085_cs, NULL,
};
struct  iomux_pin *i2c1_u9510_cs_pins[] = {
&gpio_086_cs, &gpio_087_cs, NULL,
};
struct  iomux_pin *i2c2_u9510_cs_pins[] = {
&gpio_063_cs, &gpio_064_cs, NULL,
};
struct  iomux_pin *i2c3_u9510_cs_pins[] = {
&gpio_057_cs, &gpio_058_cs, NULL,
};
struct  iomux_pin *spi0_u9510_cs_pins[] = {
&gpio_106_cs, &gpio_107_cs, &gpio_108_cs, NULL,
};
struct  iomux_pin *spi0_cs_u9510_cs_pins[] = {
&gpio_109_cs, &gpio_110_cs, &gpio_111_cs, &gpio_112_cs, NULL,
};
struct  iomux_pin *uart0_u9510_cs_pins[] = {
&gpio_119_cs, &gpio_120_cs, NULL,
};
struct  iomux_pin *uart1_u9510_cs_pins[] = {
&gpio_121_cs, &gpio_122_cs, &gpio_123_cs, &gpio_124_cs, NULL,
};
struct  iomux_pin *uart2_u9510_cs_pins[] = {
&gpio_127_cs, &gpio_128_cs, NULL,
};
struct  iomux_pin *uart4_u9510_cs_pins[] = {
&gpio_162_cs, &gpio_163_cs, &gpio_164_cs, &gpio_165_cs, NULL,
};
struct  iomux_pin *kpc_u9510_cs_pins[] = {
&gpio_129_cs, &gpio_130_cs, &gpio_131_cs, &gpio_137_cs, &gpio_138_cs, &gpio_139_cs, NULL,
};
struct  iomux_pin *sd_u9510_cs_pins[] = {
&gpio_088_cs, &gpio_089_cs, &gpio_090_cs, &gpio_091_cs, &gpio_092_cs, &gpio_093_cs, NULL,
};
struct  iomux_pin *nand_u9510_cs_pins[] = {
&gpio_008_cs, &gpio_009_cs, &gpio_010_cs, &gpio_011_cs, &gpio_012_cs, &gpio_013_cs, &gpio_014_cs, &gpio_015_cs, &gpio_016_cs, &gpio_017_cs, &gpio_018_cs, &gpio_019_cs, &gpio_020_cs, &gpio_021_cs, &gpio_022_cs, &gpio_023_cs, &gpio_024_cs, &gpio_025_cs, &gpio_026_cs, &gpio_027_cs, &gpio_028_cs, &gpio_029_cs, &gpio_030_cs, &gpio_031_cs, &gpio_032_cs, &gpio_033_cs, &gpio_034_cs, &gpio_035_cs, NULL,
};
struct  iomux_pin *sdio_u9510_cs_pins[] = {
&gpio_100_cs, &gpio_101_cs, &gpio_102_cs, &gpio_103_cs, &gpio_104_cs, &gpio_105_cs, NULL,
};
struct  iomux_pin *btpm_u9510_cs_pins[] = {
&gpio_166_cs, &gpio_167_cs, NULL,
};
struct  iomux_pin *btpwr_u9510_cs_pins[] = {
&gpio_168_cs, &gpio_169_cs, NULL,
};
struct  iomux_pin *gps_boardcom_u9510_cs_pins[] = {
&gpio_151_cs, &gpio_152_cs, NULL,
};
struct  iomux_pin *ts_u9510_cs_pins[] = {
&gpio_156_cs, &gpio_157_cs, NULL,
};
struct  iomux_pin *lcd_u9510_cs_pins[] = {
&gpio_003_cs, &gpio_072_cs, &gpio_135_cs, &gpio_136_cs, &gpio_171_cs, NULL,
};
struct  iomux_pin *pwm_u9510_cs_pins[] = {
&gpio_149_cs, &gpio_150_cs, NULL,
};
struct  iomux_pin *hdmi_u9510_cs_pins[] = {
&gpio_038_cs, &gpio_039_cs, &gpio_040_cs, &gpio_041_cs, NULL,
};
struct  iomux_pin *wifi_u9510_cs_pins[] = {
&gpio_002_cs, &gpio_004_cs, NULL,
};
struct  iomux_pin *isp_dvp_u9510_cs_pins[] = {
&gpio_042_cs, &gpio_043_cs, &gpio_044_cs, &gpio_045_cs, &gpio_046_cs, &gpio_047_cs, &gpio_048_cs, &gpio_049_cs, &gpio_052_cs, &gpio_053_cs, &gpio_054_cs, NULL,
};
struct  iomux_pin *isp_i2c_u9510_cs_pins[] = {
&gpio_055_cs, &gpio_056_cs, NULL,
};
struct  iomux_pin *isp_reset_u9510_cs_pins[] = {
&gpio_059_cs, &gpio_060_cs, NULL,
};
struct  iomux_pin *isp_u9510_cs_pins[] = {
&gpio_067_cs, &gpio_068_cs, &gpio_069_cs, &gpio_070_cs, &gpio_071_cs, &gpio_073_cs, &gpio_075_cs, NULL,
};
struct  iomux_pin *isp_flash_u9510_cs_pins[] = {
&gpio_065_cs, &gpio_066_cs, &gpio_076_cs, NULL,
};
struct  iomux_pin *charger_u9510_cs_pins[] = {
&gpio_005_cs, &gpio_074_cs, NULL,
};
struct  iomux_pin *gsensor_u9510_cs_pins[] = {
&gpio_051_cs, &gpio_148_cs, NULL,
};
struct  iomux_pin *audio_spk_u9510_cs_pins[] = {
&gpio_117_cs, NULL,
};
struct  iomux_pin *audio_eph_u9510_cs_pins[] = {
&gpio_118_cs, NULL,
};
struct  iomux_pin *modem_u9510_cs_pins[] = {
&gpio_094_cs, &gpio_095_cs, &gpio_096_cs, &gpio_097_cs, &gpio_098_cs, &gpio_113_cs, &gpio_114_cs, &gpio_115_cs, NULL,
};
struct  iomux_pin *vbusdrv_u9510_cs_pins[] = {
&gpio_082_cs, NULL,
};
struct  iomux_pin *gps_spi_u9510_cs_pins[] = {
&gpio_154_cs, &gpio_155_cs, &gpio_160_cs, &gpio_161_cs, NULL,
};

/******************IOMUX_BLOCK****************/

IOMUX_BLOCK(block_i2c0_u9510_cs, "block_i2c0_u9510_cs", NORMAL, i2c0_u9510_cs_pins)
IOMUX_BLOCK(block_i2c1_u9510_cs, "block_i2c1_u9510_cs", NORMAL, i2c1_u9510_cs_pins)
IOMUX_BLOCK(block_i2c2_u9510_cs, "block_i2c2_u9510_cs", NORMAL, i2c2_u9510_cs_pins)
IOMUX_BLOCK(block_i2c3_u9510_cs, "block_i2c3_u9510_cs", NORMAL, i2c3_u9510_cs_pins)
IOMUX_BLOCK(block_spi0_u9510_cs, "block_spi0_u9510_cs", NORMAL, spi0_u9510_cs_pins)
IOMUX_BLOCK(block_spi0_cs_u9510_cs, "block_spi0_cs_u9510_cs", NORMAL, spi0_cs_u9510_cs_pins)
IOMUX_BLOCK(block_uart0_u9510_cs, "block_uart0_u9510_cs", NORMAL, uart0_u9510_cs_pins)
IOMUX_BLOCK(block_uart1_u9510_cs, "block_uart1_u9510_cs", NORMAL, uart1_u9510_cs_pins)
IOMUX_BLOCK(block_uart2_u9510_cs, "block_uart2_u9510_cs", NORMAL, uart2_u9510_cs_pins)
IOMUX_BLOCK(block_uart4_u9510_cs, "block_uart4_u9510_cs", NORMAL, uart4_u9510_cs_pins)
IOMUX_BLOCK(block_kpc_u9510_cs, "block_kpc_u9510_cs", NORMAL, kpc_u9510_cs_pins)
IOMUX_BLOCK(block_sd_u9510_cs, "block_sd_u9510_cs", NORMAL, sd_u9510_cs_pins)
IOMUX_BLOCK(block_nand_u9510_cs, "block_nand_u9510_cs", NORMAL, nand_u9510_cs_pins)
IOMUX_BLOCK(block_sdio_u9510_cs, "block_sdio_u9510_cs", NORMAL, sdio_u9510_cs_pins)
IOMUX_BLOCK(block_btpm_u9510_cs, "block_btpm_u9510_cs", NORMAL, btpm_u9510_cs_pins)
IOMUX_BLOCK(block_btpwr_u9510_cs, "block_btpwr_u9510_cs", NORMAL, btpwr_u9510_cs_pins)
IOMUX_BLOCK(block_gps_boardcom_u9510_cs, "block_gps_boardcom_u9510_cs", NORMAL, gps_boardcom_u9510_cs_pins)
IOMUX_BLOCK(block_ts_u9510_cs, "block_ts_u9510_cs", NORMAL, ts_u9510_cs_pins)
IOMUX_BLOCK(block_lcd_u9510_cs, "block_lcd_u9510_cs", NORMAL, lcd_u9510_cs_pins)
IOMUX_BLOCK(block_pwm_u9510_cs, "block_pwm_u9510_cs", NORMAL, pwm_u9510_cs_pins)
IOMUX_BLOCK(block_hdmi_u9510_cs, "block_hdmi_u9510_cs", NORMAL, hdmi_u9510_cs_pins)
IOMUX_BLOCK(block_wifi_u9510_cs, "block_wifi_u9510_cs", NORMAL, wifi_u9510_cs_pins)
IOMUX_BLOCK(block_isp_dvp_u9510_cs, "block_isp_dvp_u9510_cs", NORMAL, isp_dvp_u9510_cs_pins)
IOMUX_BLOCK(block_isp_i2c_u9510_cs, "block_isp_i2c_u9510_cs", NORMAL, isp_i2c_u9510_cs_pins)
IOMUX_BLOCK(block_isp_reset_u9510_cs, "block_isp_reset_u9510_cs", NORMAL, isp_reset_u9510_cs_pins)
IOMUX_BLOCK(block_isp_u9510_cs, "block_isp_u9510_cs", NORMAL, isp_u9510_cs_pins)
IOMUX_BLOCK(block_isp_flash_u9510_cs, "block_isp_flash_u9510_cs", NORMAL, isp_flash_u9510_cs_pins)
IOMUX_BLOCK(block_charger_u9510_cs, "block_charger_u9510_cs", NORMAL, charger_u9510_cs_pins)
IOMUX_BLOCK(block_gsensor_u9510_cs, "block_gsensor_u9510_cs", NORMAL, gsensor_u9510_cs_pins)
IOMUX_BLOCK(block_audio_spk_u9510_cs, "block_audio_spk_u9510_cs", NORMAL, audio_spk_u9510_cs_pins)
IOMUX_BLOCK(block_audio_eph_u9510_cs, "block_audio_eph_u9510_cs", NORMAL, audio_eph_u9510_cs_pins)
IOMUX_BLOCK(block_modem_u9510_cs, "block_modem_u9510_cs", NORMAL, modem_u9510_cs_pins)
IOMUX_BLOCK(block_vbusdrv_u9510_cs, "block_vbusdrv_u9510_cs", NORMAL, vbusdrv_u9510_cs_pins)
IOMUX_BLOCK(block_gps_spi_u9510_cs, "block_gps_spi_u9510_cs", NORMAL, gps_spi_u9510_cs_pins)

/******************normal func ****************/

enum lowlayer_func i2c0_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func i2c1_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func i2c2_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func i2c3_u9510_cs_func_normal[] = {FUNC2, FUNC2, -INVALID,};
enum lowlayer_func spi0_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func spi0_cs_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func uart0_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func uart1_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func uart2_u9510_cs_func_normal[] = {FUNC2, FUNC2, -INVALID,};
enum lowlayer_func uart4_u9510_cs_func_normal[] = {FUNC2, FUNC2, FUNC2, FUNC2, -INVALID,};
enum lowlayer_func kpc_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func sd_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func nand_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func sdio_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func btpm_u9510_cs_func_normal[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func btpwr_u9510_cs_func_normal[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func gps_boardcom_u9510_cs_func_normal[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func ts_u9510_cs_func_normal[] = {RESERVE, RESERVE, -INVALID,};
enum lowlayer_func lcd_u9510_cs_func_normal[] = {FUNC0, FUNC2, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func pwm_u9510_cs_func_normal[] = {FUNC0, FUNC1, -INVALID,};
enum lowlayer_func hdmi_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func wifi_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func isp_dvp_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func isp_i2c_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func isp_reset_u9510_cs_func_normal[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func isp_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func isp_flash_u9510_cs_func_normal[] = {FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func charger_u9510_cs_func_normal[] = {FUNC0, FUNC1, -INVALID,};
enum lowlayer_func gsensor_u9510_cs_func_normal[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func audio_spk_u9510_cs_func_normal[] = {FUNC1, -INVALID,};
enum lowlayer_func audio_eph_u9510_cs_func_normal[] = {FUNC1, -INVALID,};
enum lowlayer_func modem_u9510_cs_func_normal[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func vbusdrv_u9510_cs_func_normal[] = {FUNC1, -INVALID,};
enum lowlayer_func gps_spi_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};

/******************lowpower func****************/

enum lowlayer_func i2c0_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func i2c1_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func i2c2_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func i2c3_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func spi0_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func spi0_cs_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func uart0_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func uart1_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func uart2_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func uart4_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func kpc_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func sd_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func nand_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func sdio_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func btpm_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func btpwr_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func gps_boardcom_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func ts_u9510_cs_func_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum lowlayer_func lcd_u9510_cs_func_lowpower[] = {FUNC0, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func pwm_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func hdmi_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func wifi_u9510_cs_func_lowpower[] = {FUNC0, FUNC0, -INVALID,};
enum lowlayer_func isp_dvp_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func isp_i2c_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func isp_reset_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func isp_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC0, -INVALID,};
enum lowlayer_func isp_flash_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func charger_u9510_cs_func_lowpower[] = {FUNC0, FUNC1, -INVALID,};
enum lowlayer_func gsensor_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func audio_spk_u9510_cs_func_lowpower[] = {FUNC1, -INVALID,};
enum lowlayer_func audio_eph_u9510_cs_func_lowpower[] = {FUNC1, -INVALID,};
enum lowlayer_func modem_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func vbusdrv_u9510_cs_func_lowpower[] = {FUNC0, -INVALID,};
enum lowlayer_func gps_spi_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};

/******************normal pullud****************/

enum pull_updown i2c0_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown i2c1_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown i2c2_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown i2c3_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown spi0_u9510_cs_pullud_normal[] = {PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown spi0_cs_u9510_cs_pullud_normal[] = {PULLDOWN, PULLDOWN, NOPULL, NOPULL, -INVALID,};
enum pull_updown uart0_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown uart1_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown uart2_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown uart4_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown kpc_u9510_cs_pullud_normal[] = {PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, -INVALID,};
enum pull_updown sd_u9510_cs_pullud_normal[] = {NOPULL, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, -INVALID,};
enum pull_updown nand_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown sdio_u9510_cs_pullud_normal[] = {NOPULL, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, -INVALID,};
enum pull_updown btpm_u9510_cs_pullud_normal[] = {PULLUP, NOPULL, -INVALID,};
enum pull_updown btpwr_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown gps_boardcom_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown ts_u9510_cs_pullud_normal[] = {NOPULL, PULLUP, -INVALID,};
enum pull_updown lcd_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown pwm_u9510_cs_pullud_normal[] = {NOPULL, PULLDOWN, -INVALID,};
enum pull_updown hdmi_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown wifi_u9510_cs_pullud_normal[] = {NOPULL, PULLDOWN, -INVALID,};
enum pull_updown isp_dvp_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown isp_i2c_u9510_cs_pullud_normal[] = {PULLUP, PULLUP, -INVALID,};
enum pull_updown isp_reset_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown isp_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown isp_flash_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown charger_u9510_cs_pullud_normal[] = {PULLUP, NOPULL, -INVALID,};
enum pull_updown gsensor_u9510_cs_pullud_normal[] = {PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown audio_spk_u9510_cs_pullud_normal[] = {NOPULL, -INVALID,};
enum pull_updown audio_eph_u9510_cs_pullud_normal[] = {NOPULL, -INVALID,};
enum pull_updown modem_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown vbusdrv_u9510_cs_pullud_normal[] = {NOPULL, -INVALID,};
enum pull_updown gps_spi_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, PULLDOWN, -INVALID,};

/******************lowpower pullud****************/

enum pull_updown i2c0_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown i2c1_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown i2c2_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown i2c3_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown spi0_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown spi0_cs_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, NOPULL, NOPULL, -INVALID,};
enum pull_updown uart0_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown uart1_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown uart2_u9510_cs_pullud_lowpower[] = {PULLDOWN, NOPULL, -INVALID,};
enum pull_updown uart4_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown kpc_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLUP, PULLUP, PULLDOWN, -INVALID,};
enum pull_updown sd_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown nand_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown sdio_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown btpm_u9510_cs_pullud_lowpower[] = {PULLDOWN, NOPULL, -INVALID,};
enum pull_updown btpwr_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown gps_boardcom_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown ts_u9510_cs_pullud_lowpower[] = {NOPULL, PULLUP, -INVALID,};
enum pull_updown lcd_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown pwm_u9510_cs_pullud_lowpower[] = {NOPULL, PULLDOWN, -INVALID,};
enum pull_updown hdmi_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown wifi_u9510_cs_pullud_lowpower[] = {NOPULL, PULLDOWN, -INVALID,};
enum pull_updown isp_dvp_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown isp_i2c_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown isp_reset_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown isp_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown isp_flash_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown charger_u9510_cs_pullud_lowpower[] = {PULLUP, NOPULL, -INVALID,};
enum pull_updown gsensor_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown audio_spk_u9510_cs_pullud_lowpower[] = {NOPULL, -INVALID,};
enum pull_updown audio_eph_u9510_cs_pullud_lowpower[] = {NOPULL, -INVALID,};
enum pull_updown modem_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, NOPULL, NOPULL, PULLDOWN, PULLDOWN, NOPULL, NOPULL, -INVALID,};
enum pull_updown vbusdrv_u9510_cs_pullud_lowpower[] = {NOPULL, -INVALID,};
enum pull_updown gps_spi_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};

/******************normal drv****************/

enum drive_strength i2c0_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength i2c1_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength i2c2_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength i2c3_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength spi0_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength spi0_cs_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength uart0_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength uart1_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength uart2_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength uart4_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength kpc_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength sd_u9510_cs_drv_normal[] = {LEVEL2, LEVEL3, LEVEL3, LEVEL3, LEVEL3, LEVEL3, -INVALID,};
enum drive_strength nand_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, RESERVE, RESERVE, RESERVE, RESERVE, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength sdio_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength btpm_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength btpwr_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength gps_boardcom_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength ts_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength lcd_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength pwm_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength hdmi_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength wifi_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_dvp_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_i2c_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_reset_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_u9510_cs_drv_normal[] = {LEVEL0, LEVEL0, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_flash_u9510_cs_drv_normal[] = {RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength charger_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength gsensor_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength audio_spk_u9510_cs_drv_normal[] = {RESERVE, -INVALID,};
enum drive_strength audio_eph_u9510_cs_drv_normal[] = {RESERVE, -INVALID,};
enum drive_strength modem_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength vbusdrv_u9510_cs_drv_normal[] = {LEVEL2, -INVALID,};
enum drive_strength gps_spi_u9510_cs_drv_normal[] = {LEVEL2, RESERVE, LEVEL2, LEVEL2, -INVALID,};

/******************lowpower drv****************/

enum drive_strength i2c0_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength i2c1_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength i2c2_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength i2c3_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength spi0_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength spi0_cs_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength uart0_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength uart1_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength uart2_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength uart4_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength kpc_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength sd_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL3, LEVEL3, LEVEL3, LEVEL3, LEVEL3, -INVALID,};
enum drive_strength nand_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, RESERVE, RESERVE, RESERVE, RESERVE, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL0, LEVEL0, LEVEL0, LEVEL0, LEVEL0, LEVEL0, LEVEL0, LEVEL0, -INVALID,};
enum drive_strength sdio_u9510_cs_drv_lowpower[] = {LEVEL0, LEVEL0, LEVEL0, LEVEL0, LEVEL0, LEVEL0, -INVALID,};
enum drive_strength btpm_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength btpwr_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength gps_boardcom_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength ts_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength lcd_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength pwm_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, -INVALID,};
enum drive_strength hdmi_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength wifi_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_dvp_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_i2c_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_reset_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_u9510_cs_drv_lowpower[] = {LEVEL0, LEVEL0, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength isp_flash_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, -INVALID,};
enum drive_strength charger_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength gsensor_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength audio_spk_u9510_cs_drv_lowpower[] = {RESERVE, -INVALID,};
enum drive_strength audio_eph_u9510_cs_drv_lowpower[] = {RESERVE, -INVALID,};
enum drive_strength modem_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength vbusdrv_u9510_cs_drv_lowpower[] = {LEVEL2, -INVALID,};
enum drive_strength gps_spi_u9510_cs_drv_lowpower[] = {LEVEL2, RESERVE, LEVEL2, LEVEL2, -INVALID,};

/******************config****************/

struct block_config i2c0_u9510_cs_config[] = {
	[NORMAL] = {i2c0_u9510_cs_func_normal, i2c0_u9510_cs_pullud_normal, i2c0_u9510_cs_drv_normal},
	[LOWPOWER] = {i2c0_u9510_cs_func_lowpower, i2c0_u9510_cs_pullud_lowpower, i2c0_u9510_cs_drv_lowpower},
};
struct block_config i2c1_u9510_cs_config[] = {
	[NORMAL] = {i2c1_u9510_cs_func_normal, i2c1_u9510_cs_pullud_normal, i2c1_u9510_cs_drv_normal},
	[LOWPOWER] = {i2c1_u9510_cs_func_lowpower, i2c1_u9510_cs_pullud_lowpower, i2c1_u9510_cs_drv_lowpower},
};
struct block_config i2c2_u9510_cs_config[] = {
	[NORMAL] = {i2c2_u9510_cs_func_normal, i2c2_u9510_cs_pullud_normal, i2c2_u9510_cs_drv_normal},
	[LOWPOWER] = {i2c2_u9510_cs_func_lowpower, i2c2_u9510_cs_pullud_lowpower, i2c2_u9510_cs_drv_lowpower},
};
struct block_config i2c3_u9510_cs_config[] = {
	[NORMAL] = {i2c3_u9510_cs_func_normal, i2c3_u9510_cs_pullud_normal, i2c3_u9510_cs_drv_normal},
	[LOWPOWER] = {i2c3_u9510_cs_func_lowpower, i2c3_u9510_cs_pullud_lowpower, i2c3_u9510_cs_drv_lowpower},
};
struct block_config spi0_u9510_cs_config[] = {
	[NORMAL] = {spi0_u9510_cs_func_normal, spi0_u9510_cs_pullud_normal, spi0_u9510_cs_drv_normal},
	[LOWPOWER] = {spi0_u9510_cs_func_lowpower, spi0_u9510_cs_pullud_lowpower, spi0_u9510_cs_drv_lowpower},
};
struct block_config spi0_cs_u9510_cs_config[] = {
	[NORMAL] = {spi0_cs_u9510_cs_func_normal, spi0_cs_u9510_cs_pullud_normal, spi0_cs_u9510_cs_drv_normal},
	[LOWPOWER] = {spi0_cs_u9510_cs_func_lowpower, spi0_cs_u9510_cs_pullud_lowpower, spi0_cs_u9510_cs_drv_lowpower},
};
struct block_config uart0_u9510_cs_config[] = {
	[NORMAL] = {uart0_u9510_cs_func_normal, uart0_u9510_cs_pullud_normal, uart0_u9510_cs_drv_normal},
	[LOWPOWER] = {uart0_u9510_cs_func_lowpower, uart0_u9510_cs_pullud_lowpower, uart0_u9510_cs_drv_lowpower},
};
struct block_config uart1_u9510_cs_config[] = {
	[NORMAL] = {uart1_u9510_cs_func_normal, uart1_u9510_cs_pullud_normal, uart1_u9510_cs_drv_normal},
	[LOWPOWER] = {uart1_u9510_cs_func_lowpower, uart1_u9510_cs_pullud_lowpower, uart1_u9510_cs_drv_lowpower},
};
struct block_config uart2_u9510_cs_config[] = {
	[NORMAL] = {uart2_u9510_cs_func_normal, uart2_u9510_cs_pullud_normal, uart2_u9510_cs_drv_normal},
	[LOWPOWER] = {uart2_u9510_cs_func_lowpower, uart2_u9510_cs_pullud_lowpower, uart2_u9510_cs_drv_lowpower},
};
struct block_config uart4_u9510_cs_config[] = {
	[NORMAL] = {uart4_u9510_cs_func_normal, uart4_u9510_cs_pullud_normal, uart4_u9510_cs_drv_normal},
	[LOWPOWER] = {uart4_u9510_cs_func_lowpower, uart4_u9510_cs_pullud_lowpower, uart4_u9510_cs_drv_lowpower},
};
struct block_config kpc_u9510_cs_config[] = {
	[NORMAL] = {kpc_u9510_cs_func_normal, kpc_u9510_cs_pullud_normal, kpc_u9510_cs_drv_normal},
	[LOWPOWER] = {kpc_u9510_cs_func_lowpower, kpc_u9510_cs_pullud_lowpower, kpc_u9510_cs_drv_lowpower},
};
struct block_config sd_u9510_cs_config[] = {
	[NORMAL] = {sd_u9510_cs_func_normal, sd_u9510_cs_pullud_normal, sd_u9510_cs_drv_normal},
	[LOWPOWER] = {sd_u9510_cs_func_lowpower, sd_u9510_cs_pullud_lowpower, sd_u9510_cs_drv_lowpower},
};
struct block_config nand_u9510_cs_config[] = {
	[NORMAL] = {nand_u9510_cs_func_normal, nand_u9510_cs_pullud_normal, nand_u9510_cs_drv_normal},
	[LOWPOWER] = {nand_u9510_cs_func_lowpower, nand_u9510_cs_pullud_lowpower, nand_u9510_cs_drv_lowpower},
};
struct block_config sdio_u9510_cs_config[] = {
	[NORMAL] = {sdio_u9510_cs_func_normal, sdio_u9510_cs_pullud_normal, sdio_u9510_cs_drv_normal},
	[LOWPOWER] = {sdio_u9510_cs_func_lowpower, sdio_u9510_cs_pullud_lowpower, sdio_u9510_cs_drv_lowpower},
};
struct block_config btpm_u9510_cs_config[] = {
	[NORMAL] = {btpm_u9510_cs_func_normal, btpm_u9510_cs_pullud_normal, btpm_u9510_cs_drv_normal},
	[LOWPOWER] = {btpm_u9510_cs_func_lowpower, btpm_u9510_cs_pullud_lowpower, btpm_u9510_cs_drv_lowpower},
};
struct block_config btpwr_u9510_cs_config[] = {
	[NORMAL] = {btpwr_u9510_cs_func_normal, btpwr_u9510_cs_pullud_normal, btpwr_u9510_cs_drv_normal},
	[LOWPOWER] = {btpwr_u9510_cs_func_lowpower, btpwr_u9510_cs_pullud_lowpower, btpwr_u9510_cs_drv_lowpower},
};
struct block_config gps_boardcom_u9510_cs_config[] = {
	[NORMAL] = {gps_boardcom_u9510_cs_func_normal, gps_boardcom_u9510_cs_pullud_normal, gps_boardcom_u9510_cs_drv_normal},
	[LOWPOWER] = {gps_boardcom_u9510_cs_func_lowpower, gps_boardcom_u9510_cs_pullud_lowpower, gps_boardcom_u9510_cs_drv_lowpower},
};
struct block_config ts_u9510_cs_config[] = {
	[NORMAL] = {ts_u9510_cs_func_normal, ts_u9510_cs_pullud_normal, ts_u9510_cs_drv_normal},
	[LOWPOWER] = {ts_u9510_cs_func_lowpower, ts_u9510_cs_pullud_lowpower, ts_u9510_cs_drv_lowpower},
};
struct block_config lcd_u9510_cs_config[] = {
	[NORMAL] = {lcd_u9510_cs_func_normal, lcd_u9510_cs_pullud_normal, lcd_u9510_cs_drv_normal},
	[LOWPOWER] = {lcd_u9510_cs_func_lowpower, lcd_u9510_cs_pullud_lowpower, lcd_u9510_cs_drv_lowpower},
};
struct block_config pwm_u9510_cs_config[] = {
	[NORMAL] = {pwm_u9510_cs_func_normal, pwm_u9510_cs_pullud_normal, pwm_u9510_cs_drv_normal},
	[LOWPOWER] = {pwm_u9510_cs_func_lowpower, pwm_u9510_cs_pullud_lowpower, pwm_u9510_cs_drv_lowpower},
};
struct block_config hdmi_u9510_cs_config[] = {
	[NORMAL] = {hdmi_u9510_cs_func_normal, hdmi_u9510_cs_pullud_normal, hdmi_u9510_cs_drv_normal},
	[LOWPOWER] = {hdmi_u9510_cs_func_lowpower, hdmi_u9510_cs_pullud_lowpower, hdmi_u9510_cs_drv_lowpower},
};
struct block_config wifi_u9510_cs_config[] = {
	[NORMAL] = {wifi_u9510_cs_func_normal, wifi_u9510_cs_pullud_normal, wifi_u9510_cs_drv_normal},
	[LOWPOWER] = {wifi_u9510_cs_func_lowpower, wifi_u9510_cs_pullud_lowpower, wifi_u9510_cs_drv_lowpower},
};
struct block_config isp_dvp_u9510_cs_config[] = {
	[NORMAL] = {isp_dvp_u9510_cs_func_normal, isp_dvp_u9510_cs_pullud_normal, isp_dvp_u9510_cs_drv_normal},
	[LOWPOWER] = {isp_dvp_u9510_cs_func_lowpower, isp_dvp_u9510_cs_pullud_lowpower, isp_dvp_u9510_cs_drv_lowpower},
};
struct block_config isp_i2c_u9510_cs_config[] = {
	[NORMAL] = {isp_i2c_u9510_cs_func_normal, isp_i2c_u9510_cs_pullud_normal, isp_i2c_u9510_cs_drv_normal},
	[LOWPOWER] = {isp_i2c_u9510_cs_func_lowpower, isp_i2c_u9510_cs_pullud_lowpower, isp_i2c_u9510_cs_drv_lowpower},
};
struct block_config isp_reset_u9510_cs_config[] = {
	[NORMAL] = {isp_reset_u9510_cs_func_normal, isp_reset_u9510_cs_pullud_normal, isp_reset_u9510_cs_drv_normal},
	[LOWPOWER] = {isp_reset_u9510_cs_func_lowpower, isp_reset_u9510_cs_pullud_lowpower, isp_reset_u9510_cs_drv_lowpower},
};
struct block_config isp_u9510_cs_config[] = {
	[NORMAL] = {isp_u9510_cs_func_normal, isp_u9510_cs_pullud_normal, isp_u9510_cs_drv_normal},
	[LOWPOWER] = {isp_u9510_cs_func_lowpower, isp_u9510_cs_pullud_lowpower, isp_u9510_cs_drv_lowpower},
};
struct block_config isp_flash_u9510_cs_config[] = {
	[NORMAL] = {isp_flash_u9510_cs_func_normal, isp_flash_u9510_cs_pullud_normal, isp_flash_u9510_cs_drv_normal},
	[LOWPOWER] = {isp_flash_u9510_cs_func_lowpower, isp_flash_u9510_cs_pullud_lowpower, isp_flash_u9510_cs_drv_lowpower},
};
struct block_config charger_u9510_cs_config[] = {
	[NORMAL] = {charger_u9510_cs_func_normal, charger_u9510_cs_pullud_normal, charger_u9510_cs_drv_normal},
	[LOWPOWER] = {charger_u9510_cs_func_lowpower, charger_u9510_cs_pullud_lowpower, charger_u9510_cs_drv_lowpower},
};
struct block_config gsensor_u9510_cs_config[] = {
	[NORMAL] = {gsensor_u9510_cs_func_normal, gsensor_u9510_cs_pullud_normal, gsensor_u9510_cs_drv_normal},
	[LOWPOWER] = {gsensor_u9510_cs_func_lowpower, gsensor_u9510_cs_pullud_lowpower, gsensor_u9510_cs_drv_lowpower},
};
struct block_config audio_spk_u9510_cs_config[] = {
	[NORMAL] = {audio_spk_u9510_cs_func_normal, audio_spk_u9510_cs_pullud_normal, audio_spk_u9510_cs_drv_normal},
	[LOWPOWER] = {audio_spk_u9510_cs_func_lowpower, audio_spk_u9510_cs_pullud_lowpower, audio_spk_u9510_cs_drv_lowpower},
};
struct block_config audio_eph_u9510_cs_config[] = {
	[NORMAL] = {audio_eph_u9510_cs_func_normal, audio_eph_u9510_cs_pullud_normal, audio_eph_u9510_cs_drv_normal},
	[LOWPOWER] = {audio_eph_u9510_cs_func_lowpower, audio_eph_u9510_cs_pullud_lowpower, audio_eph_u9510_cs_drv_lowpower},
};
struct block_config modem_u9510_cs_config[] = {
	[NORMAL] = {modem_u9510_cs_func_normal, modem_u9510_cs_pullud_normal, modem_u9510_cs_drv_normal},
	[LOWPOWER] = {modem_u9510_cs_func_lowpower, modem_u9510_cs_pullud_lowpower, modem_u9510_cs_drv_lowpower},
};
struct block_config vbusdrv_u9510_cs_config[] = {
	[NORMAL] = {vbusdrv_u9510_cs_func_normal, vbusdrv_u9510_cs_pullud_normal, vbusdrv_u9510_cs_drv_normal},
	[LOWPOWER] = {vbusdrv_u9510_cs_func_lowpower, vbusdrv_u9510_cs_pullud_lowpower, vbusdrv_u9510_cs_drv_lowpower},
};
struct block_config gps_spi_u9510_cs_config[] = {
	[NORMAL] = {gps_spi_u9510_cs_func_normal, gps_spi_u9510_cs_pullud_normal, gps_spi_u9510_cs_drv_normal},
	[LOWPOWER] = {gps_spi_u9510_cs_func_lowpower, gps_spi_u9510_cs_pullud_lowpower, gps_spi_u9510_cs_drv_lowpower},
};


/******************pins ****************/

struct  iomux_pin *audio_es305_u9510_cs_pins[] = {
&gpio_127_cs, &gpio_128_cs, NULL,
};
struct  iomux_pin *spi1_u9510_cs_pins[] = {
&gpio_113_cs, &gpio_114_cs, &gpio_115_cs, &gpio_116_cs, NULL,
};
struct  iomux_pin *uart3_u9510_cs_pins[] = {
&gpio_154_cs, &gpio_155_cs, &gpio_160_cs, &gpio_161_cs, NULL,
};
struct  iomux_pin *emmc_u9510_cs_pins[] = {
&gpio_028_cs, &gpio_029_cs, &gpio_030_cs, &gpio_031_cs, &gpio_032_cs, &gpio_033_cs, &gpio_034_cs, &gpio_035_cs, &gpio_036_cs, &gpio_037_cs, NULL,
};

/******************IOMUX_BLOCK****************/

IOMUX_BLOCK(block_audio_es305_u9510_cs, "block_audio_es305_u9510_cs", NORMAL, audio_es305_u9510_cs_pins)
IOMUX_BLOCK(block_spi1_u9510_cs, "block_spi1_u9510_cs", NORMAL, spi1_u9510_cs_pins)
IOMUX_BLOCK(block_uart3_u9510_cs, "block_uart3_u9510_cs", NORMAL, uart3_u9510_cs_pins)
IOMUX_BLOCK(block_emmc_u9510_cs, "block_emmc_u9510_cs", NORMAL, emmc_u9510_cs_pins)

/******************normal func ****************/

enum lowlayer_func audio_es305_u9510_cs_func_normal[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func spi1_u9510_cs_func_normal[] = {FUNC0, FUNC0, FUNC0, FUNC0, -INVALID,};
enum lowlayer_func uart3_u9510_cs_func_normal[] = {FUNC2, FUNC2, FUNC2, FUNC2, -INVALID,};
enum lowlayer_func emmc_u9510_cs_func_normal[] = {FUNC2, FUNC2, FUNC2, FUNC2, FUNC2, FUNC2, FUNC2, FUNC2, FUNC2, FUNC2, -INVALID,};

/******************lowpower func****************/

enum lowlayer_func audio_es305_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, -INVALID,};
enum lowlayer_func spi1_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func uart3_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, -INVALID,};
enum lowlayer_func emmc_u9510_cs_func_lowpower[] = {FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC1, FUNC0, FUNC0, -INVALID,};

/******************normal pullud****************/

enum pull_updown audio_es305_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown spi1_u9510_cs_pullud_normal[] = {PULLUP, NOPULL, NOPULL, PULLDOWN, -INVALID,};
enum pull_updown uart3_u9510_cs_pullud_normal[] = {NOPULL, NOPULL, NOPULL, NOPULL, -INVALID,};
enum pull_updown emmc_u9510_cs_pullud_normal[] = {PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, PULLUP, NOPULL, -INVALID,};

/******************lowpower pullud****************/

enum pull_updown audio_es305_u9510_cs_pullud_lowpower[] = {NOPULL, NOPULL, -INVALID,};
enum pull_updown spi1_u9510_cs_pullud_lowpower[] = {PULLUP, NOPULL, NOPULL, PULLDOWN, -INVALID,};
enum pull_updown uart3_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};
enum pull_updown emmc_u9510_cs_pullud_lowpower[] = {PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, PULLDOWN, -INVALID,};

/******************normal drv****************/

enum drive_strength audio_es305_u9510_cs_drv_normal[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength spi1_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength uart3_u9510_cs_drv_normal[] = {LEVEL2, RESERVE, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength emmc_u9510_cs_drv_normal[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};

/******************lowpower drv****************/

enum drive_strength audio_es305_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, -INVALID,};
enum drive_strength spi1_u9510_cs_drv_lowpower[] = {LEVEL2, LEVEL2, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength uart3_u9510_cs_drv_lowpower[] = {LEVEL2, RESERVE, LEVEL2, LEVEL2, -INVALID,};
enum drive_strength emmc_u9510_cs_drv_lowpower[] = {RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, RESERVE, -INVALID,};

/******************config****************/

struct block_config audio_es305_u9510_cs_config[] = {
	[NORMAL] = {audio_es305_u9510_cs_func_normal, audio_es305_u9510_cs_pullud_normal, audio_es305_u9510_cs_drv_normal},
	[LOWPOWER] = {audio_es305_u9510_cs_func_lowpower, audio_es305_u9510_cs_pullud_lowpower, audio_es305_u9510_cs_drv_lowpower},
};
struct block_config spi1_u9510_cs_config[] = {
	[NORMAL] = {spi1_u9510_cs_func_normal, spi1_u9510_cs_pullud_normal, spi1_u9510_cs_drv_normal},
	[LOWPOWER] = {spi1_u9510_cs_func_lowpower, spi1_u9510_cs_pullud_lowpower, spi1_u9510_cs_drv_lowpower},
};
struct block_config uart3_u9510_cs_config[] = {
	[NORMAL] = {uart3_u9510_cs_func_normal, uart3_u9510_cs_pullud_normal, uart3_u9510_cs_drv_normal},
	[LOWPOWER] = {uart3_u9510_cs_func_lowpower, uart3_u9510_cs_pullud_lowpower, uart3_u9510_cs_drv_lowpower},
};
struct block_config emmc_u9510_cs_config[] = {
	[NORMAL] = {emmc_u9510_cs_func_normal, emmc_u9510_cs_pullud_normal, emmc_u9510_cs_drv_normal},
	[LOWPOWER] = {emmc_u9510_cs_func_lowpower, emmc_u9510_cs_pullud_lowpower, emmc_u9510_cs_drv_lowpower},
};

struct block_table block_config_phone_u9510_cs[] = {
     BLOCK_CONFIG("block_i2c0", &block_i2c0_u9510_cs, i2c0_u9510_cs_config)
     BLOCK_CONFIG("block_i2c1", &block_i2c1_u9510_cs, i2c1_u9510_cs_config)
     BLOCK_CONFIG("block_i2c2", &block_i2c2_u9510_cs, i2c2_u9510_cs_config)
     BLOCK_CONFIG("block_i2c3", &block_i2c3_u9510_cs, i2c3_u9510_cs_config)
     BLOCK_CONFIG("block_spi0", &block_spi0_u9510_cs, spi0_u9510_cs_config)
     BLOCK_CONFIG("block_spi0_cs", &block_spi0_cs_u9510_cs, spi0_cs_u9510_cs_config)
     BLOCK_CONFIG("block_uart0", &block_uart0_u9510_cs, uart0_u9510_cs_config)
     BLOCK_CONFIG("block_uart1", &block_uart1_u9510_cs, uart1_u9510_cs_config)
     BLOCK_CONFIG("block_uart2", &block_uart2_u9510_cs, uart2_u9510_cs_config)
     BLOCK_CONFIG("block_uart4", &block_uart4_u9510_cs, uart4_u9510_cs_config)
     BLOCK_CONFIG("block_kpc", &block_kpc_u9510_cs, kpc_u9510_cs_config)
     BLOCK_CONFIG("block_sd", &block_sd_u9510_cs, sd_u9510_cs_config)
     BLOCK_CONFIG("block_nand", &block_nand_u9510_cs, nand_u9510_cs_config)
     BLOCK_CONFIG("block_sdio", &block_sdio_u9510_cs, sdio_u9510_cs_config)
     BLOCK_CONFIG("block_btpm", &block_btpm_u9510_cs, btpm_u9510_cs_config)
     BLOCK_CONFIG("block_btpwr", &block_btpwr_u9510_cs, btpwr_u9510_cs_config)
     BLOCK_CONFIG("block_gps_boardcom", &block_gps_boardcom_u9510_cs, gps_boardcom_u9510_cs_config)
     BLOCK_CONFIG("block_ts", &block_ts_u9510_cs, ts_u9510_cs_config)
     BLOCK_CONFIG("block_lcd", &block_lcd_u9510_cs, lcd_u9510_cs_config)
     BLOCK_CONFIG("block_pwm", &block_pwm_u9510_cs, pwm_u9510_cs_config)
     BLOCK_CONFIG("block_hdmi", &block_hdmi_u9510_cs, hdmi_u9510_cs_config)
     BLOCK_CONFIG("block_wifi", &block_wifi_u9510_cs, wifi_u9510_cs_config)
     BLOCK_CONFIG("block_isp_dvp", &block_isp_dvp_u9510_cs, isp_dvp_u9510_cs_config)
     BLOCK_CONFIG("block_isp_i2c", &block_isp_i2c_u9510_cs, isp_i2c_u9510_cs_config)
     BLOCK_CONFIG("block_isp_reset", &block_isp_reset_u9510_cs, isp_reset_u9510_cs_config)
     BLOCK_CONFIG("block_isp", &block_isp_u9510_cs, isp_u9510_cs_config)
     BLOCK_CONFIG("block_isp_flash", &block_isp_flash_u9510_cs, isp_flash_u9510_cs_config)
     BLOCK_CONFIG("block_charger", &block_charger_u9510_cs, charger_u9510_cs_config)
     BLOCK_CONFIG("block_gsensor", &block_gsensor_u9510_cs, gsensor_u9510_cs_config)
     BLOCK_CONFIG("block_audio_spk", &block_audio_spk_u9510_cs, audio_spk_u9510_cs_config)
     BLOCK_CONFIG("block_audio_eph", &block_audio_eph_u9510_cs, audio_eph_u9510_cs_config)
     BLOCK_CONFIG("block_modem", &block_modem_u9510_cs, modem_u9510_cs_config)
     BLOCK_CONFIG("block_vbusdrv", &block_vbusdrv_u9510_cs, vbusdrv_u9510_cs_config)
     BLOCK_CONFIG("block_gps_spi", &block_gps_spi_u9510_cs, gps_spi_u9510_cs_config)
     BLOCK_CONFIG("block_audio_es305", &block_audio_es305_u9510_cs, audio_es305_u9510_cs_config)
     BLOCK_CONFIG("block_spi1", &block_spi1_u9510_cs, spi1_u9510_cs_config)
     BLOCK_CONFIG("block_uart3", &block_uart3_u9510_cs, uart3_u9510_cs_config)
     BLOCK_CONFIG("block_emmc", &block_emmc_u9510_cs, emmc_u9510_cs_config)
     {NULL, NULL, NULL},
};

#endif